DROP TABLE IF EXISTS
    dbo.DoctorsPartners,
    dbo.TreatmentsMedicines,
    dbo.Apprentices,
    dbo.Bills,
    dbo.Patients,
    dbo.Doctors,
    dbo.ICUs,
    dbo.Treatments,
    dbo.Medicines,
    dbo.Watchmen,
    dbo.Nurses,
    dbo.OperationTheaters,
    dbo.Rooms,
    dbo.Partners,
    dbo.Employees,
    dbo.Shifts;
